/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BookTest {
    @Test void testBookConstructor() {
        Book book = new Book("Animal Farm", "George Orwell", "1234567890");
        assertEquals("Animal Farm", book.getTitle());
        assertEquals("George Orwell", book.getAuthor());
        assertEquals("1234567890", book.getYearPublished());
    }
}
